### PR TITLE
Fix disappearing line issue

### PR DESCRIPTION
**Pull request by jamen**
I was having an issue where it would make the line before the prompt disappear.

### CODE REVIEW

**Comment by derhuerst** [comment]
This doesn't fix the issue properly. In fact, the `-1` are in there for a reason (I don't remember anymore, but am sure about its existence).

Will change the code [to use `require('cli-styles').clear()` like in `text-prompt`](https://github.com/derhuerst/text-prompt/commit/1f527e5b2ec1da2c597433e0e8a0249a98a4da90).

**Comment by jamen** [comment]
That was actually me adding the `- 1` to fix the issue I was having.

Regardless, sounds good to use that.  Wasn't sure how to test existing prompts if this broke anything.

**Comment by derhuerst** [comment]
I finally fixed this with 93fe18c. :sweat:

**Comment by jamen** [comment]
Thanks!  :smile:

**Pull request closed without merging**
