### PR TITLE
Let the user specify their own key and value for the suggestions

### PR DESCRIPTION
**Pull request by ntwcklng**
Hi Jannis,

one of the problems i encountered when i first used this module was that i haven't used `title`for the key and `value` for the value.
This pull request let the user speficy their own key and value like this:

``` javascript
const autocompletePrompt = require('cli-autocomplete')

const colors = [
    {name: 'red',    val: '#f00'},
    {name: 'yellow', val: '#ff0'},
    {name: 'green',  val: '#0f0'},
    {name: 'blue',   val: '#00f'},
    {name: 'black',  val: '#000'},
    {name: 'white',  val: '#fff'}
]
const suggestColors = (input) => Promise.resolve(colors
    .filter((color) => color.name.slice(0, input.length) === input))

autocompletePrompt('What is your favorite color?', suggestColors, {suggestKey: 'name', suggestValue: 'val'})
.on('data', (e) => console.log('Interim value', e.value))
.on('abort', (v) => console.log('Aborted with', v))
.on('submit', (v) => console.log('Submitted with', v))
```

The defaults remain `title` for the key and `value` for the value, so it won't break existing projects.

### CODE REVIEW

**Comment by derhuerst** [comment]
Can't you just use `suggestColors` to map over the results and put them in the right shape?

**Comment by ntwcklng** [comment]
Oh okay, i thought this is the easiest way to do it, so the user does not have to.

Instead of merging this PR i can maybe write a more versatile doc/example?

**Comment by derhuerst** [comment]
> Instead of merging this PR i can maybe write a more versatile doc/example?

I could write something like this:

``` js
const colors = [
  ['red', '#f00'],
  ['green', '#0f0']
  // …
]
const suggestColors = (query) => Promise.resolve(colors
  .filter(/* … */)
  .map((c) => ({title: c[0], value: [1]})))
```

But imho the easiest example is best in the docs. The above code would just confuse people

**Comment by ntwcklng** [comment]
Ok, nevermind

**Pull request closed without merging**
